### ISSUE TITLE
Captions shouldn't start with numbers

### ISSUE THREAD

**Issue by razzeee** [flathub/io.gitlab.jazztickets.emptyclip#1]
Hey there,

I think image captions shouldn't start with numbers as that assumes a certain order and is not really useful to the user.

Cheers

**Comment by jazztickets** [comment]
It was an attempt to get screenshots to order correctly according to a comment here: https://github.com/flathub/flathub/issues/2994

**Comment by jazztickets** [comment]
It should be fixed in the next version.

**Comment by razzeee** [comment]
Thank you
